services:

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  parser:
    build:
      context: .
      dockerfile: ./parsers/Dockerfile
    restart: on-failure
    volumes:
      - ./parsers:/app/parsers
    env_file:
      - .env
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: on-failure
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    ports:
      - '8000:8001'
    depends_on:
      - db

volumes:
  pg_data: